- hosts: dpdkserver,!dpdkclient,!kvmhost
  tasks:
    - name: Install server data files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0600
      loop:
        - { src: 'server/Dockerfile', dest: '/root/Dockerfile' }
      become: true

    - name: Install server scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0700
      loop:
        - { src: 'server/create-pods.sh', dest: '/root/create-pods.sh' }
        - { src: 'server/start-pods.sh', dest: '/root/start-pods.sh' }
        - { src: 'server/stop-pods.sh', dest: '/root/stop-pods.sh' }
        - { src: 'server/entry.sh', dest: '/root/entry.sh' }
        - { src: 'server/get-tcp.sh', dest: '/root/get-tcp.sh' }
        - { src: 'server/set-tcp.sh', dest: '/root/set-tcp.sh' }
      become: true

    - name: Create containers on the VM host
      become: true
      command: sh /root/create-pods.sh
