- hosts: dpdkclient,!dpdkserver,!kvmhost
  tasks:
    - name: Install client data files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0600
      loop:
        - { src: 'client/Dockerfile', dest: '/root/Dockerfile' }
        - { src: 'client/qperf-cont.cron', dest: '/root/qperf-cont.cron' }
        - { src: 'client/qperf-client.cron', dest: '/root/qperf-client.cron' }
      become: true

    - name: Install client scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0700
      loop:
        - { src: 'client/qperf-test.sh', dest: '/root/qperf-test.sh' }
        - { src: 'client/create-pods.sh', dest: '/root/create-pods.sh' }
        - { src: 'client/start-pods.sh', dest: '/root/start-pods.sh' }
        - { src: 'client/stop-pods.sh', dest: '/root/stop-pods.sh' }
        - { src: 'client/enable-pods.sh', dest: '/root/enable-pods.sh' }
        - { src: 'client/disable-pods.sh', dest: '/root/disable-pods.sh' }
        - { src: 'client/entry.sh', dest: '/root/entry.sh' }
        - { src: 'client/get-tcp.sh', dest: '/root/get-tcp.sh' }
        - { src: 'client/set-tcp.sh', dest: '/root/set-tcp.sh' }
        - { src: 'client/temp-tcp.sh', dest: '/root/temp-tcp.sh' }
        - { src: 'client/vhost.sh', dest: '/root/vhost.sh' }
        - { src: 'client/qperf-quick.sh', dest: '/root/qperf-quick.sh' }
        - { src: 'client/qperf-client.sh', dest: '/root/qperf-client.sh' }
      become: true

    - name: Create containers on the VM host
      become: true
      command: sh /root/create-pods.sh

    - name: Install qperf container script in crontab
      become: true
      command: /usr/bin/crontab /root/qperf-cont.cron
