---
## YAML based inventory, see:
## https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
#
# Example using mix of distros
# Overriding some defaults at hostgroup and individual guest levels
# Note that the virt_infra_variant are not set to specific versions,
# this is to make it work on different hosts
# Note also that CentOS 8 needs the path to system Python
dpdkservertuned:
  hosts:
    dpdk-server-tuned-[0:3]:
      virt_infra_root_password: "password"
      virt_infra_ram: "4096"
      virt_infra_cpus: "4"
      virt_infra_cpu_numa: "cell0.id=0"
      virt_infra_cpu_numa_cpus: "0-3"
      virt_infra_numatune: "8,mode=strict"
      virt_infra_memorybacking: "hugepages=on,size=1024,unit=M"
      virt_infra_state: running
      virt_infra_variant: centos7.0
      ###########################################
      # Use for ppc64le
      ###########################################
      virt_infra_distro_image: CentOS-8-GenericCloud-8.2.2004-20200611.2.ppc64le.qcow2
      virt_infra_distro_image_url: https://cloud.centos.org/centos/8/ppc64le/images/CentOS-8-GenericCloud-8.2.2004-20200611.2.ppc64le.qcow2
      virt_infra_distro_image_checksum_url: https://cloud.centos.org/centos/8/ppc64le/images/CHECKSUM
      virt_infra_machine_type: pseries
      virt_infra_graphics: none
      ###########################################
      # Use for x86_64
      ###########################################
      # virt_infra_distro_image: CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.qcow2
      # virt_infra_distro_image_url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.qcow2
      # virt_infra_distro_image_checksum_url: https://cloud.centos.org/centos/8/x86_64/images/CHECKSUM
      # virt_infra_machine_type: q35
      # virt_infra_graphics: none
      # virt_infra_graphics: spice
      ###########################################
      ansible_python_interpreter: /usr/libexec/platform-python
    dpdk-server-tuned-0:
      virt_infra_cpuset: "80-83"
    dpdk-server-tuned-1:
      virt_infra_cpuset: "88-91"
    dpdk-server-tuned-2:
      virt_infra_cpuset: "96-99"
    dpdk-server-tuned-3:
      virt_infra_cpuset: "104-107"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    virt_infra_disks:
      - name: "boot"
        bus: "virtio"
        size: "20"
    virt_infra_networks:
      - name: "default"
